CREATE TABLE Student (
StudentID INTEGER,
StudentName NVARCHAR(25) NOT NULL,
CONSTRAINT Student_PK PRIMARY KEY(StudentID));


CREATE TABLE Faculty (
FacultyID INTEGER,
FacultyName NVARCHAR(25),
CONSTRAINT Faculty_PK PRIMARY KEY(FacultyID));

CREATE TABLE COURSE (
CourseID NVARCHAR (8),
CourseName NVARCHAR(15),
CONSTRAINT Course_PK PRIMARY KEY(CourseID));

CREATE TABLE QUALIFIED (
FacultyID INTEGER,
CourseID NVARCHAR(8),
DateQualified DATE,
CONSTRAINT Qualified_PK PRIMARY KEY (FacultyID, CourseID),
CONSTRAINT Qualified_FK1 FOREIGN KEY (FacultyID) REFERENCES Faculty (FacultyID),
CONSTRAINT Qualified_FK2 FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID));

CREATE TABLE SECTION (
SectionNo INTEGER,
Semester NVARCHAR(7),
CourseID NVARCHAR (8),
CONSTRAINT Section_PK PRIMARY KEY (SectionNo),
CONSTRAINT Section_FK FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID));

CREATE TABLE REGISTRATION (
StudentID INTEGER,
SectionNo INTEGER,
Semester NVARCHAR(7),
CONSTRAINT REGISTRATION_PK PRIMARY KEY (StudentID, SectionNo),
CONSTRAINT REGISTRATION_FK1 FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID),
CONSTRAINT REGISTRATION_FK2 FOREIGN KEY (SectionNo) REFERENCES SECTION (SectionNo));